### ISSUE TITLE
verify reconnection functionality

### ISSUE THREAD

**Issue by kortemik** [teragrep/jla_05#8]
while used for spark2.4 driver logs we see following:
```
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470)
	at com.teragrep.rlp_01.RelpConnection.sendRelpRequestAsync(RelpConnection.java:388)
	at com.teragrep.rlp_01.RelpConnection.sendBatch(RelpConnection.java:244)
	at com.teragrep.rlp_01.RelpConnection.commit(RelpConnection.java:214)
	at com.teragrep.jla_05.RelpAppender.append(RelpAppender.java:235)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:498)
	at org.apache.spark.util.SignalUtils$$anonfun$registerLogger$1$$anonfun$apply$1.apply$mcZ$sp(SignalUtils.scala:43)
	at org.apache.spark.util.SignalUtils$ActionHandler$$anonfun$2.apply(SignalUtils.scala:99)
	at org.apache.spark.util.SignalUtils$ActionHandler$$anonfun$2.apply(SignalUtils.scala:99)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.util.SignalUtils$ActionHandler.handle(SignalUtils.scala:99)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by kortemik** [comment]
please add logging to successful reconnect
